services:
  backend:
    build: ./back-end
    ports:
      - "5252:5252"
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./front-end
    ports:
      - "9000:9000"
    depends_on:
      - backend
